//! prost-generated protobuf types for the AOSP update_metadata.proto.
//!
//! This module includes the code generated by prost-build at compile time.
//! Key types: DeltaArchiveManifest, PartitionUpdate, InstallOperation, Extent,
//! PartitionInfo, Signatures, DynamicPartitionMetadata.

/// Generated protobuf types from `chromeos_update_engine` package.
pub mod chromeos_update_engine {
    include!(concat!(env!("OUT_DIR"), "/chromeos_update_engine.rs"));
}

// Re-export the most commonly used types at module level for convenience.
pub use chromeos_update_engine::install_operation::Type as OpType;
pub use chromeos_update_engine::{
    DeltaArchiveManifest, DynamicPartitionMetadata, Extent, InstallOperation, PartitionInfo,
    PartitionUpdate, Signatures,
};
