//! Integration tests running each corpus fixture through the full pipeline.
//!
//! These tests verify end-to-end behavior: sniff → analyze → extract → verify.
//! They use the synthetic fixtures generated by the `corpus-gen` crate.
//!
//! Run: `cargo test --test integration_corpus`

use forge_payload::proto::{
    DeltaArchiveManifest, Extent, InstallOperation, OpType, PartitionInfo, PartitionUpdate,
};
use forge_sniff::{MagicBytes, PackageFamily, SupportTier};
use forge_verification::hex_encode;
use prost::Message;
use sha2::{Digest, Sha256};
use std::io::Cursor;

// ===========================================================================
// Helpers — build synthetic payloads inline for determinism
// ===========================================================================

/// Deterministic partition data generator (same logic as corpus-gen).
fn generate_partition_data(pattern: &[u8], size: usize) -> Vec<u8> {
    let mut data = Vec::with_capacity(size);
    while data.len() < size {
        let chunk = pattern.len().min(size - data.len());
        data.extend_from_slice(&pattern[..chunk]);
    }
    data.truncate(size);
    data
}

fn sha256_bytes(data: &[u8]) -> Vec<u8> {
    let mut hasher = Sha256::new();
    hasher.update(data);
    hasher.finalize().to_vec()
}

fn build_payload_bin(manifest: &DeltaArchiveManifest, data_blobs: &[&[u8]]) -> Vec<u8> {
    let manifest_bytes = manifest.encode_to_vec();
    let manifest_size = manifest_bytes.len() as u64;
    let sig_size = 0u32;

    let mut payload = Vec::new();
    payload.extend_from_slice(b"CrAU");
    payload.extend_from_slice(&2u64.to_be_bytes());
    payload.extend_from_slice(&manifest_size.to_be_bytes());
    payload.extend_from_slice(&sig_size.to_be_bytes());
    payload.extend_from_slice(&manifest_bytes);
    for blob in data_blobs {
        payload.extend_from_slice(blob);
    }
    payload
}

/// Build the standard full OTA fixture inline.
fn make_full_ota_payload() -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let boot_data = generate_partition_data(b"FORGE_BOOT_IMG_", 65536);
    let vbmeta_data = generate_partition_data(b"FORGE_VBMETA__", 4096);

    let boot_hash = sha256_bytes(&boot_data);
    let vbmeta_hash = sha256_bytes(&vbmeta_data);

    let manifest = DeltaArchiveManifest {
        block_size: Some(4096),
        minor_version: Some(0),
        partitions: vec![
            PartitionUpdate {
                partition_name: "boot".to_string(),
                new_partition_info: Some(PartitionInfo {
                    size: Some(boot_data.len() as u64),
                    hash: Some(boot_hash),
                }),
                operations: vec![InstallOperation {
                    r#type: OpType::Replace as i32,
                    data_offset: Some(0),
                    data_length: Some(boot_data.len() as u64),
                    dst_extents: vec![Extent {
                        start_block: Some(0),
                        num_blocks: Some(boot_data.len() as u64 / 4096),
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            },
            PartitionUpdate {
                partition_name: "vbmeta".to_string(),
                new_partition_info: Some(PartitionInfo {
                    size: Some(vbmeta_data.len() as u64),
                    hash: Some(sha256_bytes(&vbmeta_data)),
                }),
                operations: vec![InstallOperation {
                    r#type: OpType::Replace as i32,
                    data_offset: Some(boot_data.len() as u64),
                    data_length: Some(vbmeta_data.len() as u64),
                    dst_extents: vec![Extent {
                        start_block: Some(0),
                        num_blocks: Some(vbmeta_data.len() as u64 / 4096),
                    }],
                    ..Default::default()
                }],
                ..Default::default()
            },
        ],
        security_patch_level: Some("2026-04-05".to_string()),
        max_timestamp: Some(1744848000),
        ..Default::default()
    };

    let payload = build_payload_bin(&manifest, &[&boot_data, &vbmeta_data]);
    (payload, boot_data, vbmeta_data)
}

// ===========================================================================
// Sniff tests
// ===========================================================================

#[test]
fn test_valid_full_ota_sniff_detects_crau_magic() {
    let (payload, _, _) = make_full_ota_payload();
    let mut cursor = Cursor::new(&payload);

    let result = forge_sniff::sniff(&mut cursor).unwrap();

    assert_eq!(result.magic, MagicBytes::CrauPayload);
    assert_eq!(result.family, PackageFamily::StandalonePayload);
    assert_eq!(result.tier, SupportTier::Supported);
}

#[test]
fn test_incremental_payload_sniff_detects_crau_magic() {
    let manifest = DeltaArchiveManifest {
        block_size: Some(4096),
        minor_version: Some(5),
        partitions: vec![PartitionUpdate {
            partition_name: "system".to_string(),
            operations: vec![InstallOperation {
                r#type: OpType::SourceCopy as i32,
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    };
    let payload = build_payload_bin(&manifest, &[]);
    let mut cursor = Cursor::new(&payload);

    let result = forge_sniff::sniff(&mut cursor).unwrap();
    assert_eq!(result.magic, MagicBytes::CrauPayload);
    // Sniff alone doesn't distinguish full/incremental — that's analysis
    assert_eq!(result.tier, SupportTier::Supported);
}

#[test]
fn test_unknown_magic_bytes_classified_as_forensic() {
    let data = vec![0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10]; // JPEG header
    let mut cursor = Cursor::new(&data);

    let result = forge_sniff::sniff(&mut cursor).unwrap();
    assert_eq!(result.family, PackageFamily::Unknown);
    assert_eq!(result.tier, SupportTier::Forensic);
}

// ===========================================================================
// Analysis tests
// ===========================================================================

#[test]
fn test_valid_full_ota_analyzes_as_supported() {
    let (payload, _, _) = make_full_ota_payload();
    let mut cursor = Cursor::new(&payload);

    let result = forge_payload::analysis::analyze(
        &mut cursor,
        PackageFamily::StandalonePayload,
        SupportTier::Supported,
    )
    .unwrap();

    assert_eq!(result.support_tier, "Supported");
    assert!(!result.is_incremental);
    assert_eq!(result.major_version, 2);
    assert_eq!(result.minor_version, 0);
    assert_eq!(result.partition_count, 2);
    assert_eq!(result.partitions[0].name, "boot");
    assert_eq!(result.partitions[0].category, "boot_critical");
    assert_eq!(result.partitions[1].name, "vbmeta");
    assert_eq!(result.partitions[1].category, "boot_critical");
    assert_eq!(result.security_patch_level, Some("2026-04-05".to_string()));
}

#[test]
fn test_incremental_payload_analyzes_as_experimental() {
    let manifest = DeltaArchiveManifest {
        block_size: Some(4096),
        minor_version: Some(5),
        partitions: vec![PartitionUpdate {
            partition_name: "system".to_string(),
            new_partition_info: Some(PartitionInfo {
                size: Some(8192),
                hash: Some(vec![0xCC; 32]),
            }),
            old_partition_info: Some(PartitionInfo {
                size: Some(8192),
                hash: Some(vec![0xDD; 32]),
            }),
            operations: vec![InstallOperation {
                r#type: OpType::SourceCopy as i32,
                src_extents: vec![Extent {
                    start_block: Some(0),
                    num_blocks: Some(2),
                }],
                dst_extents: vec![Extent {
                    start_block: Some(0),
                    num_blocks: Some(2),
                }],
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    };
    let payload = build_payload_bin(&manifest, &[]);
    let mut cursor = Cursor::new(&payload);

    let result = forge_payload::analysis::analyze(
        &mut cursor,
        PackageFamily::StandalonePayload,
        SupportTier::Supported,
    )
    .unwrap();

    assert_eq!(result.support_tier, "Experimental");
    assert!(result.is_incremental);
    assert_eq!(result.minor_version, 5);
    assert!(result.partitions[0].has_source_ops);
    assert!(result.partitions[0].source_hash.is_some());
}

// ===========================================================================
// End-to-end extraction + verification tests
// ===========================================================================

#[test]
fn test_valid_full_ota_extracts_boot_and_verifies_hash() {
    let (payload, boot_data, _) = make_full_ota_payload();
    let mut source = Cursor::new(&payload);

    // Parse header
    let header = forge_payload::parse_header(&mut source).unwrap();

    // Read manifest
    std::io::Seek::seek(&mut source, std::io::SeekFrom::Start(header.manifest_offset())).unwrap();
    let mut manifest_bytes = vec![0u8; header.manifest_size as usize];
    std::io::Read::read_exact(&mut source, &mut manifest_bytes).unwrap();
    let parsed = forge_payload::parse_manifest(&manifest_bytes).unwrap();

    // Find boot partition
    let boot_pu = parsed
        .manifest
        .partitions
        .iter()
        .find(|p| p.partition_name == "boot")
        .expect("boot partition not found");

    // Extract
    let mut output = Cursor::new(Vec::new());
    let cancel = std::sync::atomic::AtomicBool::new(false);

    let outcome = forge_payload::extract_partition(
        &mut source,
        &mut output,
        boot_pu,
        header.data_offset(),
        parsed.block_size,
        &cancel,
        |_| {},
    )
    .unwrap();

    // Verify extraction output matches original data
    let output_bytes = output.into_inner();
    assert_eq!(&output_bytes[..boot_data.len()], boot_data.as_slice());
    assert_eq!(outcome.bytes_extracted, boot_data.len() as u64);

    // Verify SHA-256 matches manifest target hash
    let expected_hash = boot_pu
        .new_partition_info
        .as_ref()
        .unwrap()
        .hash
        .as_ref()
        .unwrap();
    let actual_hash_bytes =
        forge_verification::hex_decode(&outcome.sha256).expect("Invalid hex in sha256");
    let verification = forge_verification::verify_hash(expected_hash, &actual_hash_bytes);
    assert_eq!(
        verification,
        forge_verification::VerificationOutcome::Verified,
        "Boot partition SHA-256 did not verify! expected={}, actual={}",
        hex_encode(expected_hash),
        outcome.sha256,
    );
}

#[test]
fn test_valid_full_ota_extracts_vbmeta_and_verifies_hash() {
    let (payload, _, vbmeta_data) = make_full_ota_payload();
    let mut source = Cursor::new(&payload);

    let header = forge_payload::parse_header(&mut source).unwrap();
    std::io::Seek::seek(&mut source, std::io::SeekFrom::Start(header.manifest_offset())).unwrap();
    let mut manifest_bytes = vec![0u8; header.manifest_size as usize];
    std::io::Read::read_exact(&mut source, &mut manifest_bytes).unwrap();
    let parsed = forge_payload::parse_manifest(&manifest_bytes).unwrap();

    let vbmeta_pu = parsed
        .manifest
        .partitions
        .iter()
        .find(|p| p.partition_name == "vbmeta")
        .expect("vbmeta partition not found");

    let mut output = Cursor::new(Vec::new());
    let cancel = std::sync::atomic::AtomicBool::new(false);

    let outcome = forge_payload::extract_partition(
        &mut source,
        &mut output,
        vbmeta_pu,
        header.data_offset(),
        parsed.block_size,
        &cancel,
        |_| {},
    )
    .unwrap();

    let output_bytes = output.into_inner();
    assert_eq!(&output_bytes[..vbmeta_data.len()], vbmeta_data.as_slice());

    let expected_hash = vbmeta_pu
        .new_partition_info
        .as_ref()
        .unwrap()
        .hash
        .as_ref()
        .unwrap();
    let actual_hash_bytes =
        forge_verification::hex_decode(&outcome.sha256).expect("Invalid hex");
    let verification = forge_verification::verify_hash(expected_hash, &actual_hash_bytes);
    assert_eq!(verification, forge_verification::VerificationOutcome::Verified);
}

// ===========================================================================
// Error path tests
// ===========================================================================

#[test]
fn test_corrupted_manifest_returns_structured_error() {
    let garbage_manifest = vec![0xFF, 0xFE, 0xFD, 0xFC, 0xFB, 0xFA, 0xF9, 0xF8];
    let manifest_size = garbage_manifest.len() as u64;

    let mut payload = Vec::new();
    payload.extend_from_slice(b"CrAU");
    payload.extend_from_slice(&2u64.to_be_bytes());
    payload.extend_from_slice(&manifest_size.to_be_bytes());
    payload.extend_from_slice(&0u32.to_be_bytes());
    payload.extend_from_slice(&garbage_manifest);

    let header = forge_payload::parse_header(&mut Cursor::new(&payload)).unwrap();

    let mut reader = Cursor::new(&payload);
    std::io::Seek::seek(
        &mut reader,
        std::io::SeekFrom::Start(header.manifest_offset()),
    )
    .unwrap();
    let mut manifest_bytes = vec![0u8; header.manifest_size as usize];
    std::io::Read::read_exact(&mut reader, &mut manifest_bytes).unwrap();

    let result = forge_payload::parse_manifest(&manifest_bytes);
    assert!(
        result.is_err(),
        "Corrupted manifest should fail parsing"
    );
    // Verify it's a specific error type, not a panic
    let err = result.unwrap_err();
    let msg = format!("{err}");
    assert!(
        !msg.is_empty(),
        "Error should have diagnostic context"
    );
}

#[test]
fn test_truncated_payload_returns_manifest_corrupt() {
    let mut payload = Vec::new();
    payload.extend_from_slice(b"CrAU");
    payload.extend_from_slice(&2u64.to_be_bytes());
    payload.extend_from_slice(&1024u64.to_be_bytes()); // claims 1024B manifest
    payload.extend_from_slice(&0u32.to_be_bytes());
    payload.extend_from_slice(&[0x08, 0x01, 0x10, 0x00]); // only 4B present

    let header = forge_payload::parse_header(&mut Cursor::new(&payload)).unwrap();
    assert_eq!(header.manifest_size, 1024);

    // Attempt to read manifest bytes — should fail (truncated)
    let mut reader = Cursor::new(&payload);
    std::io::Seek::seek(
        &mut reader,
        std::io::SeekFrom::Start(header.manifest_offset()),
    )
    .unwrap();

    let mut manifest_bytes = vec![0u8; header.manifest_size as usize];
    let read_result = std::io::Read::read_exact(&mut reader, &mut manifest_bytes);
    assert!(
        read_result.is_err(),
        "Reading truncated manifest should fail with UnexpectedEof"
    );
}

#[test]
fn test_incremental_source_copy_extraction_returns_unsupported_error() {
    let manifest = DeltaArchiveManifest {
        block_size: Some(4096),
        minor_version: Some(5),
        partitions: vec![PartitionUpdate {
            partition_name: "system".to_string(),
            new_partition_info: Some(PartitionInfo {
                size: Some(8192),
                hash: None,
            }),
            operations: vec![InstallOperation {
                r#type: OpType::SourceCopy as i32,
                src_extents: vec![Extent {
                    start_block: Some(0),
                    num_blocks: Some(2),
                }],
                dst_extents: vec![Extent {
                    start_block: Some(0),
                    num_blocks: Some(2),
                }],
                ..Default::default()
            }],
            ..Default::default()
        }],
        ..Default::default()
    };
    let payload = build_payload_bin(&manifest, &[]);
    let mut source = Cursor::new(&payload);

    let header = forge_payload::parse_header(&mut source).unwrap();
    std::io::Seek::seek(&mut source, std::io::SeekFrom::Start(header.manifest_offset())).unwrap();
    let mut manifest_bytes = vec![0u8; header.manifest_size as usize];
    std::io::Read::read_exact(&mut source, &mut manifest_bytes).unwrap();
    let parsed = forge_payload::parse_manifest(&manifest_bytes).unwrap();

    let system_pu = &parsed.manifest.partitions[0];
    let mut output = Cursor::new(vec![0u8; 8192]);
    let cancel = std::sync::atomic::AtomicBool::new(false);

    let result = forge_payload::extract_partition(
        &mut source,
        &mut output,
        system_pu,
        header.data_offset(),
        parsed.block_size,
        &cancel,
        |_| {},
    );

    assert!(
        matches!(
            result,
            Err(forge_payload::ExtractionError::UnsupportedOperation { .. })
        ),
        "SOURCE_COPY without source should return UnsupportedOperation, got: {result:?}"
    );
}

// ===========================================================================
// ZIP-based sniff tests
// ===========================================================================

#[test]
fn test_zip_with_payload_bin_classified_as_aosp_ota() {
    // Build a minimal ZIP with a payload.bin entry
    let mut zip_bytes = Vec::new();
    {
        let cursor = Cursor::new(&mut zip_bytes);
        let mut zip = zip::ZipWriter::new(cursor);
        let options = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Stored);

        zip.start_file("payload.bin", options).unwrap();
        // Just need the entry name — content can be minimal CrAU header
        zip.write_all(b"CrAU").unwrap();
        zip.write_all(&2u64.to_be_bytes()).unwrap();
        zip.write_all(&0u64.to_be_bytes()).unwrap(); // 0-length manifest
        zip.write_all(&0u32.to_be_bytes()).unwrap();

        zip.finish().unwrap();
    }

    let mut cursor = Cursor::new(&zip_bytes);
    let result = forge_sniff::sniff_seekable(&mut cursor).unwrap();

    assert_eq!(result.magic, MagicBytes::Zip);
    assert_eq!(result.family, PackageFamily::AospPayloadOta);
    assert_eq!(result.tier, SupportTier::Supported);
}

#[test]
fn test_zip_with_only_img_entries_classified_as_legacy_forensic() {
    let mut zip_bytes = Vec::new();
    {
        let cursor = Cursor::new(&mut zip_bytes);
        let mut zip = zip::ZipWriter::new(cursor);
        let options = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Stored);

        zip.start_file("boot.img", options).unwrap();
        zip.write_all(&[0xAA; 16]).unwrap();

        zip.start_file("system.img", options).unwrap();
        zip.write_all(&[0xBB; 16]).unwrap();

        zip.finish().unwrap();
    }

    let mut cursor = Cursor::new(&zip_bytes);
    let result = forge_sniff::sniff_seekable(&mut cursor).unwrap();

    assert_eq!(result.family, PackageFamily::LegacyImgZip);
    assert_eq!(result.tier, SupportTier::Forensic);
}

// ===========================================================================
// Analysis JSON serialization roundtrip
// ===========================================================================

#[test]
fn test_analysis_result_serializes_to_valid_json() {
    let (payload, _, _) = make_full_ota_payload();
    let mut cursor = Cursor::new(&payload);

    let result = forge_payload::analysis::analyze(
        &mut cursor,
        PackageFamily::StandalonePayload,
        SupportTier::Supported,
    )
    .unwrap();

    let json = serde_json::to_string(&result).unwrap();

    // Verify key fields are present in JSON
    assert!(json.contains("\"support_tier\":\"Supported\""));
    assert!(json.contains("\"is_incremental\":false"));
    assert!(json.contains("\"partition_count\":2"));
    assert!(json.contains("\"boot\""));
    assert!(json.contains("\"vbmeta\""));

    // Verify it round-trips (deserialize check — structure is valid)
    let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert_eq!(parsed["partition_count"], 2);
}

use std::io::Write;
